### ISSUE TITLE
Please don't automatically insert a port in the config

### ISSUE THREAD

**Issue by kolaente** [kns-it/Docker-GitPitch#1]
I use your docker container with a different public port than 9000. It works in general, but when I want to download my presentation either as pdf or zip, it fails with the message:

```
GitPitch Slideshow offline service temporarily unavailable.
```
The container logs tell me that it's trying download from the wrong URL:
```
15.2.2018 15:35:412018-02-15 14:35:41,539 application-akka.actor.default-dispatcher-3 [debug] c.g.c.PitchController - offline: pp=/gitea/kolaente/presentation/master [ white, null ]
15.2.2018 15:35:412018-02-15 14:35:41,540 application-akka.actor.default-dispatcher-3 [debug] c.g.s.PitchService - cachedZip: zipAge=1518705341540, max=1200000, file=/home/gitpitch/swap/gitea/kolaente/presentation/master/PITCHME.zip
15.2.2018 15:35:412018-02-15 14:35:41,540 application-akka.actor.default-dispatcher-3 [debug] c.g.s.PitchService - cachedZip: deleted expired zip artifacts.
15.2.2018 15:35:412018-02-15 14:35:41,541 Front-End-Pool [debug] c.g.s.PitchService - fetchZip: pp=/gitea/kolaente/presentation/master [ white, null ]
15.2.2018 15:35:412018-02-15 14:35:41,542 Front-End-Pool [debug] c.g.s.OfflineService - fetchZip: pp=/gitea/kolaente/presentation/master [ white, null ], ssmo.isPresent=true
15.2.2018 15:35:412018-02-15 14:35:41,552 Back-End-Pool [debug] c.g.s.OfflineService - generateZip: pp=/gitea/kolaente/presentation/master [ white, null ], ssmo.isPresent=true
15.2.2018 15:35:412018-02-15 14:35:41,553 Back-End-Pool [debug] c.g.s.DiskService - download: pp=/gitea/kolaente/presentation/master [ white, null ], source=http://kolaente.de:9003:9000/pitchme/markdown/gitea/kolaente/presentation/master/PITCHME.md
Unknown Date
15.2.2018 15:35:412018-02-15 14:35:41,553 Back-End-Pool [debug] c.g.s.WebService - download: pp=/gitea/kolaente/presentation/master [ white, null ], source=http://kolaente.de:9003:9000/pitchme/markdown/gitea/kolaente/presentation/master/PITCHME.md
15.2.2018 15:35:412018-02-15 14:35:41,556 Back-End-Pool [warn] c.g.s.WebService - download: failed pp=/gitea/kolaente/presentation/master [ white, null ], from source=http://kolaente.de:9003:9000/pitchme/markdown/gitea/kolaente/presentation/master/PITCHME.md, ex={}
15.2.2018 15:35:41java.lang.NumberFormatException: For input string: "9003:9000"
15.2.2018 15:35:41	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
15.2.2018 15:35:41	at java.lang.Integer.parseInt(Integer.java:580)
15.2.2018 15:35:41	at java.lang.Integer.parseInt(Integer.java:615)
15.2.2018 15:35:41	at org.asynchttpclient.uri.UriParser.computeRegularHostPort(UriParser.java:199)
15.2.2018 15:35:41	at org.asynchttpclient.uri.UriParser.parseAuthority(UriParser.java:277)
15.2.2018 15:35:41	at org.asynchttpclient.uri.UriParser.parse(UriParser.java:333)
15.2.2018 15:35:41	at org.asynchttpclient.uri.Uri.create(Uri.java:36)
15.2.2018 15:35:41	at org.asynchttpclient.uri.Uri.create(Uri.java:31)
15.2.2018 15:35:41	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:148)
15.2.2018 15:35:41	at play.libs.ws.ahc.AhcWSRequest.buildRequest(AhcWSRequest.java:461)
15.2.2018 15:35:412018-02-15 14:35:41,556 Back-End-Pool [warn] c.g.s.WebService - fetchBytes: failed pp=/gitea/kolaente/presentation/master [ white, null ], from source=http://kolaente.de:9003:9000/pitchme/markdown/gitea/kolaente/presentation/master/PITCHME.md, ex={}
15.2.2018 15:35:41java.lang.NullPointerException: null
15.2.2018 15:35:41	at com.gitpitch.services.WebService.fetchBytes(WebService.java:62)
15.2.2018 15:35:41	at com.gitpitch.services.DiskService.download(DiskService.java:155)
15.2.2018 15:35:41	at com.gitpitch.services.OfflineService.fetchOnlineMarkdown(OfflineService.java:252)
15.2.2018 15:35:41	at com.gitpitch.services.OfflineService.generateZip(OfflineService.java:186)
15.2.2018 15:35:41	at com.gitpitch.services.OfflineService.lambda$fetchZip$0(OfflineService.java:117)
15.2.2018 15:35:41	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
15.2.2018 15:35:41	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15.2.2018 15:35:41	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15.2.2018 15:35:41	at java.lang.Thread.run(Thread.java:745)
15.2.2018 15:35:412018-02-15 14:35:41,556 Back-End-Pool [warn] c.g.s.DiskService - download: pp=/gitea/kolaente/presentation/master [ white, null ], failed to download and write from source=http://kolaente.de:9003:9000/pitchme/markdown/gitea/kolaente/presentation/master/PITCHME.md
15.2.2018 15:35:412018-02-15 14:35:41,556 Back-End-Pool [warn] c.g.s.OfflineService - fetchZip: pp=/gitea/kolaente/presentation/master [ white, null ], fetch status=999
15.2.2018 15:35:412018-02-15 14:35:41,558 Front-End-Pool [debug] c.g.s.PitchService - cachedZip: zipAge=1518705341558, max=1200000, file=/home/gitpitch/swap/gitea/kolaente/presentation/master/PITCHME.zip
15.2.2018 15:35:412018-02-15 14:35:41,574 Front-End-Pool [debug] c.g.s.PitchService - cachedZip: deleted expired zip artifacts.
15.2.2018 15:35:412018-02-15 14:35:41,575 Front-End-Pool [debug] c.g.s.PitchService - fetchZip: pp=/gitea/kolaente/presentation/master [ white, null ], returning zip=null
15.2.2018 15:35:412018-02-15 14:35:41,575 Front-End-Pool [info] c.g.c.PitchController - offline:   [ failed, downld ] /gitea/kolaente/presentation/master [ white, null ]
```

Apparently it tries to download the markdown from `kolaente.de:9003:9000`, which obviously does not work, as the service is only accessible via `kolaente.de:9003` from the outside world. Looking inside the container, `hostname = "kolaente.de:9003:9000"` is set in the config which explains why it tries to get the markdown from there.

[This line](https://github.com/kns-it/Docker-GitPitch/blob/master/full/conf/application.conf.template#L362) probably needs to be changed. I think users are clever enough to set their full url correctly whith port when they use a different public port, so there's no need for the dockerimage to do this automatically.
I could provide a pr.

**Comment by prskr** [comment]
I'll have a look if that's required but I don't think so.

I'm running the container at a public domain, where the container port 9000 is published as 59000, but the reverse proxy is serving it at port 443 with HTTPS just with having set the environment variable GP_HOST to the public domain without any port and no further setup (like any HTTP reader rewrites or stuff like that)

**Comment by prskr** [comment]
I made the change you requested, it's discussable if it's better to just provide the hostname or hostname including the port but I think this way it's a little bit cleaner.

I have to improve the documentation to get that aspect clearer.

In your case the build of the `.zip` and the `.pdf` failed because the loopback call GitPitch uses to get the HTML representation of the presentation failed caused by defining the port twice as you already explained.

I think I resolved that problem by setting the hostname fixed to **localhost:9000** to ensure that the loopback calls are always done inside the container and **GP_HOST** is only evaluated for CORS and allowed hosts (so basically just for publishing mannors).

The build is running, I'll test it when it's completed and update this issue.

I used the following command to reproduce your situation:

```bash
docker run -d \
        --rm \
        --name gitpitch \
        -e GP_GITHUB_AS_DEFAULT=true \
        -e GP_HOST=gitpitch \
        -p 9003:9000 \
        knsit/gitpitch-pdf
```

maybe you can give me some feedback if that fits?

**Comment by prskr** [comment]
I validated the latest image on Docker Hub with the given command and a sample presentation and it's working like expected, could you please check if it's what you wanted to achieve?

**Comment by kolaente** [comment]
I've checked and it works, thanks very much for the quick fix!

I'm using it with this compose file:

```yaml
version: '2'
services:
  gitpitch:
    image: knsit/gitpitch-pdf:latest
    environment:
      GP_GITEA_ACCESS_TOKEN: dattoken
      GP_GITEA_API: https://git.kolaente.de/api/v1/
      GP_GITEA_AS_DEFAULT: 'true'
      GP_GITEA_BASE: https://git.kolaente.de/
      GP_HOST: gitpitch.kolaente.de
```

I have a loadbalancer in front of it, which redirects all requests to `gitpitch.kolaente.de` to that container (As of now, I had it configured in the way I described previously which I also tested - works).
